baseurl = "http://blog.hwc.io"
languageCode = "en-us"
title = "walther chen"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true

theme = "hyde"

[Author]
    name = "Walther Chen"

[permalinks]
    blog = "/:year/:month/:filename/"
    code = "/:filename/"

[taxonomies]
    tag = "tags"
    series = "series"
    series-desc = "series-desc"
    
[params]
        description = "code, Go, yoga"
        linkedin = "http://www.linkedin.com/pub/walther-chen/12/7a5/5b8"
        github = "https://github.com/hwchen"
    
